### ISSUE TITLE
[Bug]: ValueError: Empty message content

### ISSUE THREAD

**Issue by fishhead108** [Pythagora-io/gpt-pilot#1035]
### Version

VisualStudio Code extension

### Operating System

MacOS

### What happened?

Pythagora abruptly stopped with the following error:
```
Stopping Pythagora due to error:

File `core/cli/main.py`, line 37, in run_project
    success = await orca.run()
File `core/agents/orchestrator.py`, line 67, in run
    response = await agent.run()
File `core/agents/troubleshooter.py`, line 41, in run
    user_instructions = await self.get_user_instructions()
File `core/agents/troubleshooter.py`, line 143, in get_user_instructions
    route_files = await self._get_route_files()
File `core/agents/troubleshooter.py`, line 163, in _get_route_files
    self._get_task_convo()
File `core/agents/troubleshooter.py`, line 123, in _get_task_convo
    .assistant(self.current_state.current_task["instructions"])
File `core/llm/convo.py`, line 106, in assistant
    return self.add("assistant", content, name)
File `core/llm/convo.py`, line 61, in add
    raise ValueError("Empty message content")
ValueError: Empty message content
```

Versions: `Pythagora v0.2.6 / GPT Pilot v0.2.5`

![image](https://github.com/Pythagora-io/gpt-pilot/assets/2705977/bf945b1c-02d7-4173-9404-02cc70c3064f)

**Comment by LeonOstrez** [comment]
The issue here was that some data was not properly stored in DB. That caused error that you had `ValueError: Empty message content`. We published new version that should have a fix for that so that it doesn't happen again but unfortunately you will have to load the app at the start of last task and redo last task again

**Comment by quloos** [comment]
I had the issue with Pythagora v0.2.14 / GPT Pilot v0.2.8-gitc80bdfc

Stopping Pythagora due to error:

File core/cli/main.py, line 37, in runproject
    success = await orca.run()
File core/agents/orchestrator.py, line 66, in run
    response = await agent.run()
File core/agents/code_reviewer.py, line 59, in run
    approvedcontent, feedback = await self.review_change(
File core/agents/code_reviewer.py, line 140, in review_change
    llm_response: ReviewChanges = await llm(convo, temperature=0, parser=JSONParser(ReviewChanges))
File core/agents/base.py, line 182, in client
    response, request_log = await llm_client(convo, **kwargs)
File core/llm/base.py, line 286, in __call
    convo.assistant(response)
File core/llm/convo.py, line 106, in assistant
    return self.add("assistant", content, name)
File core/llm/convo.py, line 61, in add
    raise ValueError("Empty message content")
ValueError: Empty message content

**Comment by yf007** [comment]
This error came back once again, and this time in a big way!

**Comment by allintky** [comment]
I have the same problem
