### ISSUE TITLE
Developer.py - "if step['type'] == 'command':"

### ISSUE THREAD

**Issue by Captain-Bacon** [Pythagora-io/gpt-pilot#13]
Hi,

I can tell from the code that this is something to be worked on, but I just thought I'd mention that it is the thing that keeps on causing all the apps I've tried to create to fail.  

`f step['type'] == 'command':
TypeError: string indices must be integers`

I'm not entirely sure what the issue is, otherwise I'd have a bash at it - I'm not clever, just stubborn!  I've tried to print the step variable to the console, but got nothing, so I'm not much use I'm afraid.

**Comment by NoEdgeAtLife** [comment]
same thing, and better to have a list for the arguments

**Comment by zvone187** [comment]
Yea, you're right. The problem is in function calling from OpenAI. We decided to use function calling like it's some kind of a silver bullet but in reality, it often returns incorrect response. In this case, it should return the `type` flag but sometimes it doesn't even though in the JSON schema it is required to be returned. We'll need to add verification during the postprocessing after the GPT response.

**Comment by nalbion** [comment]
@zvone187 I don't understand this line in `AgentConvo.py`:

```python
        if function_calls is not None and 'function_calls' in function_calls:
            self.messages[-1]['content'] += '\nMAKE SURE THAT YOU RESPOND WITH A CORRECT JSON FORMAT!!!'
```

All of the objects in `function_calls.py` have a `functions` object, but none have a `function_calls` object...

```python
COMMANDS_TO_RUN = {
    'definitions': [
        return_array_from_prompt('commands', 'command', 'commands')
    ],
    'functions': {
        'process_commands': run_commands
    },
}
```
