### ISSUE TITLE
disable colorized output

### ISSUE THREAD

**Issue by Konfekt** [Pythagora-io/gpt-pilot#159]
Output is colorized making it impossible to read; is there something like a `--nocolor` option for plain ASCII output?

**Comment by nalbion** [comment]
Does this help? 

https://github.com/Pythagora-io/gpt-pilot/pull/160

**Comment by Konfekt** [comment]
![immagine](https://github.com/Pythagora-io/gpt-pilot/assets/7195553/bdf91681-2eb6-4da9-a9b5-92817121400c)

**Comment by nalbion** [comment]
Ah - you're using a light theme. I believe @Umpire2018 was looking into that

**Comment by Umpire2018** [comment]
@nalbion OK. Please assign me to this issue.

**Comment by Umpire2018** [comment]
Automatically detecting the terminal background color is a challenging task due to the lack of functionality or APIs provided by terminals themselves to inform running applications about their configuration. This issue is well recognized and widely discussed within the developer community.

To address this, I consider using one of the following approaches:

1. Utilizing Environment Variables:
Some users may set environment variables to indicate their terminal type, such as light or dark background. You can check these variables and adjust your color scheme accordingly. For instance, macOS's Terminal and iTerm 2 allow users to set a `TERM_PROGRAM_BACKGROUND_COLOR` environment variable.

Based on the spirit of https://no-color.org/, an informal standard was proposed in 2017:

Command-line software that adds ANSI color to its output by default should check for the presence of a `NO_COLOR` environment variable. If the variable exists and is not an empty string, regardless of its value, the addition of ANSI color should be prevented.

@nalbion FYI.

**Comment by nalbion** [comment]
@Umpire2018 I'm not on a Mac, so I'm not sure what values to expect from `TERM_PROGRAM_BACKGROUND_COLOR`, but if we could check that first, and then `NO_COLOR`, and default to the current colouring for dark mode

**Comment by Umpire2018** [comment]
@nalbion Here is what people do in no-color.org
![image](https://github.com/Pythagora-io/gpt-pilot/assets/138990495/d0a72803-8c5d-4639-93f8-c6b7aa50435d)

Another discussions of `no-color`.
https://github.com/cli/cli/issues/364
[Support NO_COLOR environment variable to disable color](https://github.com/cli/cli/pull/742/files)
