### ISSUE TITLE
Lack of possibility to edit technological stack #2

### ISSUE THREAD

**Issue by GregorD1A1** [Pythagora-io/gpt-pilot#247]
Issue was closed here https://github.com/Pythagora-io/gpt-pilot/issues/203, but rising it again, as in my opinion it totally not soved, and until it will be solved, gpt-pilot will just useless toy.

It is written in article https://blog.pythagora.ai/2023/08/23/430/, _we are still far away from an LLM that can just be hooked up to a CLI and work by itself to create any app by itself._ _to enable AI to generate a fully working app, we need to allow it to work closely with the developer who oversees the development process_. I totally agree with that assumptions, and also think there should be possibility to edit AI's work after every simple step.

So it's important to be able to edit the proposed technological stack - architect agent proposed mostly wrong one and it's almost impossible to create code further, having bad fundaments. There shold be possibility to interact with agent - same as during user stories creation, "advanced" mode don't seemed to be able to solve problem.

**Comment by bigvo** [comment]
You can easily change it in the code 
<img width="1215" alt="Screenshot 2023-10-25 at 16 55 19" src="https://github.com/Pythagora-io/gpt-pilot/assets/98709257/e932cbd2-2f57-4179-b906-8a70f36e8deb">

**Comment by sarahedwin442** [comment]
I want to use this golden medium to Appreciate Dr Kuda for making my dream come through. I was on the internet when I saw people posting and talking about Dr Kuda. On How he has help them in winning huge amounts in lottery ticket, My name is Sarah Edwin, this is my story on how I win $754.6 Million Dollars, After reading the article talking good about Dr Kuda I contacted Dr Kuda I told him to help me win the Powerball lottery, Then he respond to me by saying he will help me after working with Dr Kuda, and assured me that I will win the Powerball Lottery Draw, Which I believe. After working with Dr Kuda, he gave me a five digit number and ask me to go and play it which I did today, now i’m here shearing a testimony about this same man Dr Kuda Changed my life by helping me to win $754.6 Million Dollars all thanks to you Dr Kuda, I will keep talking about your good work, because you are a man of your word I hope people that really need this help will come across it for you to help them as well. If you want to win biggest in lottery contact Dr. Kuda today and be rest assured of winning lottery game, contact via email: drkudaspelltemple@gmail.com Or Call and Whatsapp Number +1 (346) 478-1991

**Comment by LeonOstrez** [comment]
if you run `python main.py advanced` it will add some more functionalities. One of them is generation of user stories, second one is ability to change tech stack.

Having that said, I would still suggest not using any big frameworks until we implement selection of specific files/functions when talking to LLM.

Here is example how it looks like:

<img width="1691" alt="Screenshot 2023-11-08 at 9 53 14 PM" src="https://github.com/Pythagora-io/gpt-pilot/assets/41999013/edd1cc1c-6612-40b0-95a0-042e19b0e49e">
