### ISSUE TITLE
Is postgresql better than sqlite in some way?

### ISSUE THREAD

**Issue by CRD716** [Pythagora-io/gpt-pilot#267]
If it is, why not make it the default?
If not, why have it in the requirements instead of sqlite?
If they're the same, maybe make it clear that both work the same.

**Comment by Umpire2018** [comment]
> Why not make PostgreSQL the default? 
- The simplicity and zero configuration of SQLite are more valuable than the advanced features and scalability of PostgreSQL.

> Why have PostgreSQL in the requirements instead of SQLite? 
- To offer flexibility. While SQLite is great for development or lightweight apps, PostgreSQL could be a better choice for production environments, especially when scalability and concurrent writes are concerned.

> Are they the same? 
- No, they serve different purposes, as explained above but work seamlessly with both.

Lastly, it's essential to stress that PostgreSQL is **merely an optional choice**.
BTW, i believe you already have answers when raising this issue.

**Comment by Scratch-project** [comment]
**PostgreSQL**:
1. PostgreSQL is a powerful, enterprise-grade database system known for its scalability and ability to handle complex and high-transactional workloads.
2. It supports high levels of concurrent connections and transactions, making it suitable for applications with heavy usage.


**SQLite**:
1. SQLite is a self-contained, serverless, and zero-configuration database engine. 
2. It is lightweight, simple to set up, and easy to use. It's a good choice for smaller-scale projects or when you need a local database with minimal setup.
3. SQLite is single-user and doesn't support high levels of concurrent access compared to PostgreSQL.
4. The entire database is contained within a single file, making it portable and easy to manage.

Regarding why SQLite is used as the default database in some software or requirements, it's often because of its simplicity, ease of use, and minimal setup requirements. SQLite is suitable for applications where the need for a full-fledged database server like PostgreSQL is unnecessary.

**SUM UP**: Use SQLite if you are just testing GPT-Pilot or have a small scaled website or APP as its easier to use and no need to use PostgreSQL in such cases, just more things to worry about.
