### ISSUE TITLE
Windows 11 and Ubuntu, "Cant find process" and "dublicate key value violates unique constraint"/PeeWee.

### ISSUE THREAD

**Issue by KevinGeLe** [Pythagora-io/gpt-pilot#291]
![image](https://github.com/Pythagora-io/gpt-pilot/assets/125448701/063ff32a-6ab5-48e4-804f-2704ba5c6404)
The only time that I havent gotten "Cant find process" is if it doesnt "check_if_fixed".

And I thought the dublicate error was an error on my side. But since I'm also getting it on Ubuntu im not so sure.

Also I got Github 404 when trying to view this repo a few minutes back, did it get privated?

**Comment by senko** [comment]
> ![image](https://user-images.githubusercontent.com/125448701/280394767-063ff32a-6ab5-48e4-804f-2704ba5c6404.png) The only time that I havent gotten "Cant find process" is if it doesnt "check_if_fixed".
> 
> And I thought the dublicate error was an error on my side. But since I'm also getting it on Ubuntu im not so sure.

Which database (postgres or sqlite) are you using? And could you try removing the database (you can just rm or move the file if on sqlite) and checking if this still happens? 

> Also I got Github 404 when trying to view this repo a few minutes back, did it get privated?

GitHub had some availability issues earlier in the day, lots of repos were 404'd temporarily.

**Comment by senko** [comment]
I was able to reproduce the database error with Python 3.12 on Windows 11 using SQlite database.

Here's the screenshot. The top window is sqlite3 database contents, showing the file entry. The bottom is the log where the check whether this file is already in the database fails.

![Screenshot from 2023-11-04 16-25-09](https://github.com/Pythagora-io/gpt-pilot/assets/3362/0fe33016-db9a-4f25-afb5-39c6c210653c)

The actual error happens because we try to re-insert the file entry in the database thinking it isn't there; screenshot (similar to yours):

![Screenshot from 2023-11-04 16-27-57](https://github.com/Pythagora-io/gpt-pilot/assets/3362/8874e345-5fbf-4e80-ba7d-712b4e6547b3)

The immediate cause of this error is incorrect handling of Windows paths. If you look at the two paths, you can see that in the database the path ends with `/app.js`, while the query checks for `\app.js`. On Windows, we should be always using windows-style path separators.

This happens in several places in the code so it'll take some time to fix, but I'm hoping to improve that bit of the code soon.

**Comment by KevinGeLe** [comment]
Thanks, though I was using PostgreSQL. But I still got the dublicate string on Ubuntu (Python 3.11), but maybe its another error.

**Comment by sarahedwin442** [comment]
I want to use this golden medium to Appreciate Dr Kuda for making my dream come through. I was on the internet when I saw people posting and talking about Dr Kuda. On How he has help them in winning huge amounts in lottery ticket, My name is Sarah Edwin, this is my story on how I win $754.6 Million Dollars, After reading the article talking good about Dr Kuda I contacted Dr Kuda I told him to help me win the Powerball lottery, Then he respond to me by saying he will help me after working with Dr Kuda, and assured me that I will win the Powerball Lottery Draw, Which I believe. After working with Dr Kuda, he gave me a five digit number and ask me to go and play it which I did today, now i’m here shearing a testimony about this same man Dr Kuda Changed my life by helping me to win $754.6 Million Dollars all thanks to you Dr Kuda, I will keep talking about your good work, because you are a man of your word I hope people that really need this help will come across it for you to help them as well. If you want to win biggest in lottery contact Dr. Kuda today and be rest assured of winning lottery game, contact via email: drkudaspelltemple@gmail.com Or Call and Whatsapp Number +1 (346) 478-1991
