### ISSUE TITLE
ImportError: cannot import name 'HashTrieMap' from 'rpds' 

### ISSUE THREAD

**Issue by LaNcER-Q** [Pythagora-io/gpt-pilot#297]
I'm sorry, I am a beginner, and I followed your tutorial step by step, but I encountered the ImportError: cannot import name 'HashTrieMap' from 'rpds' . I checked it myself and indeed I couldn't find the 'rpds' package. Can someone please tell me how to resolve this issue?

**Comment by senko** [comment]
Please provide the following info:

* operating system you're using (windows, macos, linux)
* version of python you're using (check with `python3 -V`)
* complete log of the installation step `pip install -r requirements.txt`
* log of the error (at least the last 15-20 lines)

**Comment by LaNcER-Q** [comment]
operating system you're using (windows, macos, linux)  
_windows_ 
version of python you're using (check with python3 -V)
_Python 3.10.11_
complete log of the installation step pip install -r requirements.txt
[installation_log.txt](https://github.com/Pythagora-io/gpt-pilot/files/13258731/installation_log.txt)

![image](https://github.com/Pythagora-io/gpt-pilot/assets/93499974/6eb0be96-c3c5-48a8-ac47-a652cad31e13)


log of the error (at least the last 15-20 lines)

_Traceback (most recent call last):
  File "D:\Download\gpt-pilot-main\pilot\main.py", line 15, in <module>
    from helpers.Project import Project
  File "D:\Download\gpt-pilot-main\pilot\helpers\Project.py", line 11, in <module>
    from prompts.prompts import ask_user
  File "D:\Download\gpt-pilot-main\pilot\prompts\prompts.py", line 5, in <module>
    from utils.llm_connection import create_gpt_chat_completion
  File "D:\Download\gpt-pilot-main\pilot\utils\llm_connection.py", line 10, in <module>
    from jsonschema import validate, ValidationError
  File "d:\users\lancer\appdata\local\programs\python\python311\lib\site-packages\jsonschema\__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "d:\users\lancer\appdata\local\programs\python\python311\lib\site-packages\jsonschema\_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "d:\users\lancer\appdata\local\programs\python\python311\lib\site-packages\jsonschema\exceptions.py", line 15, in <module>
    from referencing.exceptions import Unresolvable as _Unresolvable
  File "d:\users\lancer\appdata\local\programs\python\python311\lib\site-packages\referencing\__init__.py", line 4, in <module>
    from referencing._core import Anchor, Registry, Resource, Specification
  File "d:\users\lancer\appdata\local\programs\python\python311\lib\site-packages\referencing\_core.py", line 8, in <module>
    from rpds import HashTrieMap, HashTrieSet, List
ImportError: cannot import name 'HashTrieMap' from 'rpds' (d:\users\lancer\appdata\local\programs\python\python311\lib\site-packages\rpds\__init__.py)_

**Comment by LaNcER-Q** [comment]
I'm glad to hear that the two commands resolved the issue, and your program is now running. However, I don't know the reason behind it. It seems that the 'rpds' package version was downgraded to an older one. Could this potentially cause any problems?

```
pip unistall rpds 
pip install rpds-py==0.5.3
```

**Comment by LaNcER-Q** [comment]
Oh  sorry  
Is that means  i should pay  some money to chatGPT ?
```
API responded with status code: 429. Response text: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}
```

**Comment by LaNcER-Q** [comment]
> Please provide the following info:
> 
> * operating system you're using (windows, macos, linux)
> * version of python you're using (check with `python3 -V`)
> * complete log of the installation step `pip install -r requirements.txt`
> * log of the error (at least the last 15-20 lines)

Hello~ I type the answer blow your tips ~~ could you give me  some help ?

**Comment by senko** [comment]
> > Please provide the following info:
> Hello~ I type the answer blow your tips ~~ could you give me some help ?

Your comment https://github.com/Pythagora-io/gpt-pilot/issues/297#issuecomment-1793660128 sounded like you solved that issue and now had a problem with GPT API quota?

From your installation log, I'm not sure how you installed the packages because it only shows an error saying there's no`requirements.txt` file.

In the shell you should navigate to the project root folder (that contains file `requirements.txt`) and then run `pip install -r requirements.txt` and it shouldn't give an error. If you omitted that part, it's possible you installed incorrect package version(s) which could cause the `rpds` error you're having.

I'm afraid we can't help with quota limits on ChatGPT.

**Comment by sarahedwin442** [comment]
I want to use this golden medium to Appreciate Dr Kuda for making my dream come through. I was on the internet when I saw people posting and talking about Dr Kuda. On How he has help them in winning huge amounts in lottery ticket, My name is Sarah Edwin, this is my story on how I win $754.6 Million Dollars, After reading the article talking good about Dr Kuda I contacted Dr Kuda I told him to help me win the Powerball lottery, Then he respond to me by saying he will help me after working with Dr Kuda, and assured me that I will win the Powerball Lottery Draw, Which I believe. After working with Dr Kuda, he gave me a five digit number and ask me to go and play it which I did today, now i’m here shearing a testimony about this same man Dr Kuda Changed my life by helping me to win $754.6 Million Dollars all thanks to you Dr Kuda, I will keep talking about your good work, because you are a man of your word I hope people that really need this help will come across it for you to help them as well. If you want to win biggest in lottery contact Dr. Kuda today and be rest assured of winning lottery game, contact via email: drkudaspelltemple@gmail.com Or Call and Whatsapp Number +1 (346) 478-1991
