### ISSUE TITLE
python db_init.py is fail？help me

### ISSUE THREAD

**Issue by The-Flowers999** [Pythagora-io/gpt-pilot#301]
why I can't pass  in step of python db_init.py?   
error is :No module named 'dotenv'  (it's ok after pin install dotenv)and  No module named 'playhouse'

**Comment by The-Flowers999** [comment]
python 3.12 version

**Comment by The-Flowers999** [comment]
after Use python3.11 ，the error is ：
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 55: invalid continuation byte

**Comment by The-Flowers999** [comment]
(pilot-env) E:\gpt-pilot\pilot>python db_init.py
Traceback (most recent call last):
  File "E:\gpt-pilot\pilot\db_init.py", line 5, in <module>
    drop_tables()
  File "E:\gpt-pilot\pilot\database\database.py", line 449, in drop_tables
    with database.atomic():
  File "E:\gpt-pilot\pilot-env\Lib\site-packages\peewee.py", line 4363, in __enter__
    return self._helper.__enter__()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\gpt-pilot\pilot-env\Lib\site-packages\peewee.py", line 4398, in __enter__
    self._begin()
  File "E:\gpt-pilot\pilot-env\Lib\site-packages\peewee.py", line 4384, in _begin
    self.db.begin(*args, **kwargs)
  File "E:\gpt-pilot\pilot-env\Lib\site-packages\peewee.py", line 3390, in begin
    self.connect()
  File "E:\gpt-pilot\pilot-env\Lib\site-packages\peewee.py", line 3187, in connect
    self._state.set_connection(self._connect())
                               ^^^^^^^^^^^^^^^
  File "E:\gpt-pilot\pilot-env\Lib\site-packages\peewee.py", line 3926, in _connect
    conn = psycopg2.connect(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\gpt-pilot\pilot-env\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 55: invalid continuation byte

**Comment by sarahedwin442** [comment]
I want to use this golden medium to Appreciate Dr Kuda for making my dream come through. I was on the internet when I saw people posting and talking about Dr Kuda. On How he has help them in winning huge amounts in lottery ticket, My name is Sarah Edwin, this is my story on how I win $754.6 Million Dollars, After reading the article talking good about Dr Kuda I contacted Dr Kuda I told him to help me win the Powerball lottery, Then he respond to me by saying he will help me after working with Dr Kuda, and assured me that I will win the Powerball Lottery Draw, Which I believe. After working with Dr Kuda, he gave me a five digit number and ask me to go and play it which I did today, now i’m here shearing a testimony about this same man Dr Kuda Changed my life by helping me to win $754.6 Million Dollars all thanks to you Dr Kuda, I will keep talking about your good work, because you are a man of your word I hope people that really need this help will come across it for you to help them as well. If you want to win biggest in lottery contact Dr. Kuda today and be rest assured of winning lottery game, contact via email: drkudaspelltemple@gmail.com Or Call and Whatsapp Number +1 (346) 478-1991

**Comment by senko** [comment]
Hello!

If you have the latest version of GPT-Pilot, it should work on both Python 3.11 and Python 3.12.

`dotenv` is specified in the `requirements.txt` file and should be installed automatically (on any version of Python) if you followed the [installation process from the readme](https://github.com/Pythagora-io/gpt-pilot#how-to-start-using-gpt-pilot):

`pip install -r requirements.txt`

If there was error in that installation step, please attach the full log when running that command and we can check what the cause was.

For the second error, it looks like your `.env` file is using a text codec that's not `utf-8` and has non-ASCII (English letters) characters. Please try saving the file as `utf-8`.

**Comment by The-Flowers999** [comment]
> Hello!
> 
> If you have the latest version of GPT-Pilot, it should work on both Python 3.11 and Python 3.12.
> 
> `dotenv` is specified in the `requirements.txt` file and should be installed automatically (on any version of Python) if you followed the [installation process from the readme](https://github.com/Pythagora-io/gpt-pilot#how-to-start-using-gpt-pilot):
> 
> `pip install -r requirements.txt`
> 
> If there was error in that installation step, please attach the full log when running that command and we can check what the cause was.
> 
> For the second error, it looks like your `.env` file is using a text codec that's not `utf-8` and has non-ASCII (English letters) characters. Please try saving the file as `utf-8`.

thank  you  very much
