### ISSUE TITLE
[Enhancement]: Using GPT Pilot for existing projects

### ISSUE THREAD

**Issue by saleh-mir** [Pythagora-io/gpt-pilot#381]
Congratulation on the amazing project. It is exactly what I've been thinking project generation should be.

Is it possible to use GPT-Pilot inside a project that already has a certain amount of code in it?

Preferably, is it possible for GPT-Pilot to make the other code similar to the existing code? For example, in a web application, if I have implemented a certain number of endpoints, I need GPT-Pilot to implement the remaining functionalities similar to the previous ones.

**Comment by roscoevanderboom** [comment]
I second this feature request. It would be great to have "Create New Project" or "Import Existing Project". By pointing GPT-Pilot to a package.json file, it could understand the project details. When scanning, it could ignore certain folders like "/node_modules" to save time.

**Comment by evgenyfadeev** [comment]
or  allow cloning a git repo into the project, indexing it, learning of the technologies used and taking from there.

**Comment by svallory** [comment]
I believe this should be handled by using [aider](https://github.com/paul-gauthier/aider)

They are focused on understanding existing codebases and trying to solve that issue for large ones

In fact, maybe a merger or deeper collaboration between both projects could generate a de facto standard for coding agents

**Comment by outrank-james** [comment]
Great suggestion - would love something like this to be able to handle projects that have been going on for many years - would streamline a lot of work going forward on projects that already exist.

**Comment by cranyy** [comment]
any updates on this?

**Comment by zkewind** [comment]
Is anyone implementing this feature?

**Comment by IncomeStreamSurfer** [comment]
please god implement this feature PLEAAAAAAAAAAAAAAAAAAASE

**Comment by IncomeStreamSurfer** [comment]
i feel literally stuck on a massive project i am working on because the bot considers it finished and won't let me work on it, and i have now changed the code myself beyond its recognition. it's proving super hard to do anything. I'd love to just be able to open my code as it is currently working and then run gpt pilot. Just add a .gptpilot.ignore or whatever for all the node modules etc... plsplsplslsp do this

**Comment by 5eqn** [comment]
Some ideas about implementing this feature:

Based on my current understanding of the codebase, the following fields are required to form a valid project:

- name (just simply ask user)
- project description (just simply ask user)
- user stories (can be inferred from project description, add a confirm step for this?)
- architecture (just simply ask user)
- dependencies (extract from package.json?)
- previous features (filter implemented features from project tasks)
- future features (sort unimplemented features reasonably?)

If these can be generated, we can theoretically integrate on existing project.

How does it look?

**Comment by IncomeStreamSurfer** [comment]
> Some ideas about implementing this feature:
> 
> Based on my current understanding of the codebase, the following fields are required to form a valid project:
> 
> * name (just simply ask user)
> * project description (just simply ask user)
> * user stories (can be inferred from project description, add a confirm step for this?)
> * architecture (just simply ask user)
> * dependencies (extract from package.json?)
> * previous features (filter implemented features from project tasks)
> * future features (sort unimplemented features reasonably?)
> 
> If these can be generated, we can theoretically integrate on existing project.
> 
> How does it look?

Whatever you need to do do it - thank you

**Comment by zkewind** [comment]
I am working on it .

**Comment by zkewind** [comment]
It's done. See [PR #952.](https://github.com/Pythagora-io/gpt-pilot/pull/952)

**Comment by senko** [comment]
First, props to @zkewind for doing this!

We had the feature in our sights for a long time (too long!), and while we were working on it for 0.2 (which we just released in tandem with the VSCode extension today), I love how Jack just went ahead and did it. It really shows the power of open source and I appreciate the effort and initiative!

While we're not making changes to our 0.1 version any more it's still available (in `version-0.1` branch) and some people may not want or be able to switch and @zkewind 's PR will be very useful for them.

Now for the announcement: as of today, **loading existing project is supported out-of-the-box in gpt-pilot 0.2.x** (and if you're using our VSCode extension, in Pythagora 0.2.x). It's still experimental and also has similar limitations (and in fact works similarly to his, although we've been able to to take advantage of some of the things we reworked in our 0.2 rewrite to make it seem easy), but we do hope it'll be useful.

As can be seen from when this issue was opened, it's a long standing bug and it gives me great satisfaction to hit the "Close as complete" button on this one. I hope you'll like what we did (and if you encounter problems, file a bug or even better join us on Discord).
