### ISSUE TITLE
Interface (Visual Studio Code) / Generation slows down significantly over time.

### ISSUE THREAD

**Issue by CryptVenture** [Pythagora-io/gpt-pilot#419]
The interface when used in Visual Studio Code starts very fast and progressively gets significantly slower over time. Is this a memory issue? Or is there an issue with the extension in Visual Studio Code?

**Comment by senko** [comment]
This is likely a problem with LLM (or in general the approach that we're taking).

As you're building your application, there's more and more context (information about the project, goals, requirements, what's already created) and it takes more and more time for the LLM to process it.  Since the more information the LLM has, the better code it can produce, we want to give it as much information as possible, but at some point that does start to slow it down.

It's something we're aware of and in the process of fixing but it's likely going to take a while.

Note: if it's only the VS Code extension that's slow, and if you try to open (and continue) the same project with the command line version of GPT Pilot and it goes noticably faster, then that would indicate a possible bug in the extension. So far we haven't gotten reports of those.

**Comment by jasonnator** [comment]
I'd be happy to confirm this for you. I have a large and complex .NET MAUI project im working on and the VS Code plugin is taking over 20 minutes to process in some cases from one step to the next.

Where can I find the guid to start from the same position via the command line? I've checked my postgrea database and there are no app-ids there despite a successful db-init

**Comment by mferris77** [comment]
FWIW, when I first started testing this out, (using command line interface) everything was quite fast and then after about 30-45 minutes it slowed to a crawl - to the point where I thought it was stuck in a loop without showing any output.  I checked my account on OpenAI and saw that I had already eaten through $2 of usage (gpt-4-turbo), then tried to enter the most recent command into the playground chat box and then received an error that I had hit the rate limit and to try again later.  So that must have been why the CLI generation was slow as well.  I haven't dug through the code yet to see if knows it's being rate limited, or simply retrying after a certain interval.  But rate limiting from OpenAI could be the cause as well.

If GPT-Pilot does actually know that it's being rate-limited, it would be nice if the interface could indicate that so people don't think that the app isn't doing anything and quits out of the session.

**Comment by senko** [comment]
Thanks for providing more info!

> If GPT-Pilot does actually know that it's being rate-limited, it would be nice if the interface could indicate that so people don't think that the app isn't doing anything and quits out of the session.

This is a great suggestion!

> Where can I find the guid to start from the same position via the command line? I've checked my postgrea database and there are no app-ids there despite a successful db-init

The VSCode extension configures GPT Pilot to use SQLite. If you haven't overridden that, then the database should be in `gpt-pilot\pilot\gpt-pilot` file. If you manually go to the `pilot` folder, activate the python virtual environment (`..\pilot-env\Scripts\activate`), you should be able to run `python main.py --get-created-apps-with-steps` and find the app.

**Comment by lyndonb1** [comment]
I have seen the open api rate limit message in an `exception message from the connect status message after` hitting ctrl+c to kill the application after it was hanging a long time, so we're definitely being rate limited by open ai. They have a 500 request per minute rate limit on most models at tier 1 and 2 which most people willl be at. The message stated I had exceeded that and and I would be rate limited for some timeout period. You should change the app to stay below that rate limit and queue or pop a message for all cases

**Comment by techjeylabs** [comment]
closed after incativity
