### ISSUE TITLE
[Bug]: Problem with request to openai API

### ISSUE THREAD

**Issue by Hardeepex** [Pythagora-io/gpt-pilot#428]
### Version

VisualStudio Code extension

### Operating System

MacOS

### What happened?

There was a problem with request to openai API:
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by senko** [comment]
Thanks for reporting this! Does this happen every time you try to use GPT Pilot?

If it just happened once, it could be a temporary network error (since we didn't get any error from the openai API).

Also - if you've modified `OPENAI_ENDPOINT` in GPT Pilot settings, and get this error, it could mean the enpoint is incorrect. (If you haven't modified it or don't know about that setting, you can ignore this comment as by default we're using OpenAI).
