### ISSUE TITLE
[BUG]: Unnecessary bug solving triggered by non-running app/service.

### ISSUE THREAD

**Issue by YosuCadilla** [Pythagora-io/gpt-pilot#485]
Why do we have to "press r" to run a service we are working on each time? This triggers pointless bug solving...

I'm working on a Flask app, I have to run it (by pressing 'r') every time I need to do a test or "check if it works".
Wouldn't it be better to keep it always running and just turn it off if necessary at any point in time?

This has already caused a few times a situation where GPT-P tries to call the Python APP via curl, but it fails, because it is not started. Then it starts debugging a non-existing issue, which leads down the rabbit hole of despair...

**Comment by techjeylabs** [comment]
hey there since Extension updates ( v0.1.15 released today, Monday 15.4. )
For everyone who was annoyed that they constantly had to confirm Yes to running commands, now if you are on one of our subscription plans, you have access to Advanced settings where you can Allow command runs.
Sound notification  is another option in Advanced settings, so now, if you are running Pythagora in the background you will be notified with a sound that your input is required. We plan to add more similar customization options in Advanced settings.
