### ISSUE TITLE
Making the model that runs GPT Pilot have no cost.

### ISSUE THREAD

**Issue by TrickyyRL** [Pythagora-io/gpt-pilot#596]
### Version

VisualStudio Code extension

### Suggestion

It would be really cool if GPT Pilot had a way of using GPT-4 for free so everyone can use the extension without using up their OpenAI API key credits. I already know of GPT4Free (g4f) which is a library that provides a lot of models for free, including GPT-4 and GPT-3.5. There are the links for the github repo and pypi package:

GItHub:
https://github.com/xtekky/gpt4free

PyPI:
https://pypi.org/project/g4f

I hope you read this and actually implement this so everyone can use the extension!

**Comment by KevinGeLe** [comment]
If the licence from the models, allows it to be integrated to gpt-pilot. Then we could simple have an option under .env, named "local model=" and have it setup automatically. 

The thing is, your project is not the same as mine. If the model is too creative the temperature needs to be lowered and wiseversa. Also the models you talk about, have been trained to mimic openai's models, instead of making the dataset bigger. So alot of data that the average user doesnt need, simply isnt there. That means low quality code (if they can even do that.)

So we need bigger models? Then we also need to make sure the model can run on that specific hardware. Soooo, make a benchmark, get score and then download the appropriate model? Seems simple. Except that its hard to get a specific benchmark from the hardware, as hardware generation, cpu, gpu, ram, ai acceleration etc. Plays a huge role. 

Great idea. But unnecessary when gpt-pilot itself needs different instruction per model.


Kevin

**Comment by takimdigital** [comment]
Try this 

https://github.com/tgscan-dev/g4f-api

**Comment by techjeylabs** [comment]
hey there, as allready beeing mentioned you can do this by implementing a local llm. You can find instruction on howto do this in our wiki pages. I am closing there this request.

https://github.com/Pythagora-io/gpt-pilot/wiki/Using-GPT%E2%80%90Pilot-with-Local-LLMs
