### ISSUE TITLE
[Feature] Branch other LLM to perform the task

### ISSUE THREAD

**Issue by franckleveque** [Pythagora-io/gpt-pilot#8]
Hi,

Your article is quite interesting, I was wondering if it would be relatively simple to branch another LLM on the market (like Claude or LLaMa 2) ?

If I understood properly your files , it is https://github.com/Pythagora-io/gpt-pilot/blob/main/pilot/utils/llm_connection.py that is in charge managing the connection. Are there other part that takes care of the communication with the LLM model ?

**Comment by zvone187** [comment]
Thank you 🙏

Yes, you're right. There, you can just change the endpoint for the LLM. Unfortunately, we've used OpenAIs function calling which won't work with other LLMs so it will require a bigger refactor. The good thing is that function calling needs to be removed anyway since it doesn't work too good anyway.

**Comment by mrgoonie** [comment]
I've created [this PR](https://github.com/Pythagora-io/gpt-pilot/pull/69) with [OpenRouter API](https://openrouter.ai/) so we can use other LLM models

**Comment by LeonOstrez** [comment]
now you are able to set in .env either OPENAI or AZURE or OPENROUTER
