### ISSUE TITLE
groq rate limit by api

### ISSUE THREAD

**Issue by Soundmovin46** [Pythagora-io/gpt-pilot#862]
### Version

VisualStudio Code extension

### Operating System

Windows 11

### What happened?

i get this after a couple lines of code 
how do i stop getting this erorr 

Rate limited by the API (we're over 'tokens per minute' or 'requests per minute' limit)
Retrying in 20.387 second(s)... with extra buffer of: 20.0 second(s) 

more info about  groq User
We set the following x-ratelimit headers to inform you on current rate limits applicable to the API key and associated organization.

The following headers are set (values are illustrative):

Header	Value	Notes
retry-after	2	In seconds
x-ratelimit-limit-requests	14400	Always refers to Requests Per Day (RPD)
x-ratelimit-limit-tokens	18000	Always refers to Tokens Per Minute (TPM)
x-ratelimit-remaining-requests	14370	Always refers to Requests Per Day (RPD)
x-ratelimit-remaining-tokens	17997	Always refers to Tokens Per Minute (TPM)
x-ratelimit-reset-requests	2m59.56s	Always refers to Requests Per Day (RPD)
x-ratelimit-reset-tokens	7.66s	Always refers to Tokens Per Minute (TPM)

When the rate limit is reached we return a 429 Too Many Requests HTTP status code.

Note, retry-after is only set if you hit the rate limit and status code 429 is returned. The other headers are always included.

**Comment by azimhamza** [comment]
Your'e getting rate limited. Seems like this is intentional.

**Comment by techjeylabs** [comment]
rate limited is intentional. Its not a bug.

**Comment by debasish-mohanty** [comment]
we should give an option to control rate limit per minuite. we might compromise on time it takes to get the gorq to respond that having continous rate limit reached even after the requested wait time passed. give an option so gpt-pilot  obtains only specific token per minute  so has to handle this ratelimit . I am sure a developer will compromise on completing a project in days rather than one hour.

**Comment by sagarbhavsar1** [comment]
this is a rate or a token limit issue:
Your groq model is only intended to take in a certain number API calls per minute (rate limit)
and a certain amount of tokens per API call (token limit).
I'm assuming you are on the free tier , which is why you have such tight limits on your model.
The only solutions to get past this is to:
- either upgrade to a dev tier (more rate limits and token limits)
- Try using delays for handling rate limits, send every API call after a certain delay so that Groq is not overloaded with too many requests at a time.,, if that doesn't work:
- try batch processing (split your context (tokens) in batches and send those APIs to the model, once you have all the output from the model, converge all the batch outputs together into a final full output)
